### ISSUE TITLE
TIK TOK API

### ISSUE THREAD

**Issue by bradfordlee90** [HA6Bots/TikTok-Compilation-Video-Generator#10]
Hello, i tried the new update and i get this message:

Traceback (most recent call last):
  File "C:\Python38-32\lib\configparser.py", line 789, in get
    value = d[option]
  File "C:\Python38-32\lib\collections\__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "C:\Python38-32\lib\collections\__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 's_v_web_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tik tok bot\TikTok Server\main.py", line 4, in <module>
    import server
  File "D:\tik tok bot\TikTok Server\server.py", line 31, in <module>
    settings.generateConfigFile()
  File "D:\tik tok bot\TikTok Server\settings.py", line 75, in generateConfigFile
    loadValues()
  File "D:\tik tok bot\TikTok Server\settings.py", line 91, in loadValues
    s_v_web_id = config.get('tiktok', 's_v_web_id')
  File "C:\Python38-32\lib\configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 's_v_web_id' in section: 'tiktok'

**Comment by habibi92** [comment]
you can go on the config.ini, under Language in tiktok section, add s_v_web_id and tt_webid, it works for me

**Comment by HA6Bots** [comment]
Yes you need to update your config file with s_v_web_id and tt_webid.

**Comment by habibi92** [comment]
HA6, i've a question, i put the s_v_web and the tt_webid, but now when i'm starting it, it said tiktokapi isn't loaded, i don't understand because i re-installed the tiktok api 3 times :/

**Comment by HA6Bots** [comment]
@habibi92 Make sure you remove the previous version of the TikTokAPI via pip remove. Then install the new API. I don't think either one works when they're both installed since they share the same names.

**Comment by nisanb** [comment]
I keep getting {'statusCode': 0} in the logs. It can't find anything.
