### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peterkiers** [HA6Bots/TikTok-Compilation-Video-Generator#11]
Hey I get this Error when I try to use the Client

`Downloading Video
.mp4
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Home\Desktop\TikTok-Compilation-Video-Generator-master\TikTok Client\client.py", line 200, in downloadFinishedVideo
    ftp.retrbinary('RETR %s.mp4' % name, file.write, blocksize=settings.block_size)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "C:\Users\Home\AppData\Local\Programs\Python\Python38\lib\ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 No such file or directory.

`

can you help me?

thanks in advance, kid regards

**Comment by peterkiers** [comment]
and in the cmd from the video generator
it spams
127.0.0.1 - - [10/Feb/2021 17:53:35] "GET /getrenderinfo HTTP/1.1" 200 -
