### ISSUE TITLE
Error Downloading Clips

### ISSUE THREAD

**Issue by Mitix-EPI** [HA6Bots/TikTok-Compilation-Video-Generator#12]
In TikTokServer, when I try to dl (clicking on `Start Downloading`), there are some errors on the terminal.
I added some print to debug the thing

```
Downloading...
Downloading Clip 1/9
VideoFiles Zach King6932104074846375173
<pymediainfo.MediaInfo object at 0x0000017D3FA53940>
[<Track track_id='None', track_type='General'>]
<Track track_id='None', track_type='General'>
None
float() argument must be a string or a number, not 'NoneType'
Error downloading clip
Downloading Clip 2/9
VideoFiles user5066131102056930292632715382021
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python38\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Une connexion existante a dû être fermée par l’hôte distant
<pymediainfo.MediaInfo object at 0x0000017D3FAF6640>
[<Track track_id='None', track_type='General'>]
<Track track_id='None', track_type='General'>
None
float() argument must be a string or a number, not 'NoneType'
Error downloading clip
```
**TikTokServer/tiktok.py**
```py
try:
            api.downloadVideoById(clip.id, f"{settings.vid_filepath}/{clip.author_name}-{clip.id}.mp4")
            media_info = MediaInfo.parse(f"{settings.vid_filepath}/{clip.author_name}-{clip.id}.mp4")
            print(media_info)
            print(media_info.tracks)
            print(media_info.tracks[0])
            duration = media_info.tracks[0].duration
            print(duration)
            clip.vid_duration = float(duration) / 1000
            database.updateStatusWithClip(clip.id, "DOWNLOADED", clip)
except Exception as e:
            print(e)
            print("Error downloading clip")
            database.updateStatusWithClip(clip.id, "BAD", clip)
```

I think the error is from the MediaInfo.
`MediaInfo.parse` does not read correctly the file.

Also, when I open Clip Bin, I can't play the videos. I don't know why ? Format mp4, ~380ko. I also try to read the informations inside the videos with the MediaInfo software but impossible to read any information.

**Comment by alzeric** [comment]
This may be an issue with the avilash TikTokAPI or could be Token Related not sure right now.  If you peer into the "Broken" mp4 that get outputted into the VideoFiles folder you'll see the following. (Open with Text Editor or view with VSCode)

`<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;ve&#45;0068c003&#47;266a4097bbec490ebbb277817c074f2a&#47;&#63;" on this server.<P>
Reference&#32;&#35;18&#46;54a8ce17&#46;1616762934&#46;62c4c265
</BODY>
</HTML>
`
