### ISSUE TITLE
Error when downloading clips (client)

### ISSUE THREAD

**Issue by Ahmed-Alh** [HA6Bots/TikTok-Compilation-Video-Generator#2]
Whenever i try to start editing and then click on 'download clips' this error pops up on the command line:
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Ahmed\Desktop\TikTok-Compilation-Video-Generator\TikTok Client\client.py", line 44, in requestClips
    ftp.login(settings.FTP_USER, settings.FTP_PASSWORD)
  File "C:\Python38\lib\ftplib.py", line 403, in login
    resp = self.sendcmd('PASS ' + passwd)
  File "C:\Python38\lib\ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "C:\Python38\lib\ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 530 Authentication failed.
```
running on windows 10

**Comment by HA6Bots** [comment]
Hi Ahmed did you register a new user in the server program, and then restart it?
Also try changing the ip address in FTP address of the config of the server and client from localhost, to 127.0.0.1 and then finally a ipv4 address. Looks like this is of a issue with the library ftplib.

**Comment by HA6Bots** [comment]
Also try enter your username and password into the client config files if not already.

**Comment by Ahmed-Alh** [comment]
I've reinstalled python and wrote the username and password into the client config and now it works.
