### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by innovadorx** [HA6Bots/TikTok-Compilation-Video-Generator#3]
Traceback (most recent call last):
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 137, in getAllClips
    api = TikTokApi("browsermob-proxy/bin/browsermob-proxy")
TypeError: __init__() takes 1 positional argument but 2 were given
__init__() takes 1 positional argument but 2 were given
exception occured downloading. waiting and retrying

I think TikTokApi updated something, but the function TikTokApi() wont take 2 arguments anymore
Wont run for me

**Comment by HA6Bots** [comment]
Thanks for letting me know. I've updated the tiktok.py class now to remove the unnecessary parameter to match the 3.6 release of TikTokAPI. 
Please update the file and let me know if it's working now. 
Many thanks

**Comment by innovadorx** [comment]
> Thanks for letting me know. I've updated the tiktok.py file now to remove the unnecessary parameter to match the 3.6 release of TikTokAPI.
> Please update the file and let me know if it's working now.
> Many thanks

Hello! Thanks for your fast response 

Traceback (most recent call last):
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 150, in getAllClips
    new_ids.append(attemptAddScripts(results, "Hashtag"))
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 60, in attemptAddScripts
    videoURL = tiktok["itemInfos"]["video"]["urls"][0]
KeyError: 'itemInfos'
'itemInfos'

Im getting that error now

**Comment by innovadorx** [comment]
Traceback (most recent call last):
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 150, in getAllClips
    new_ids.append(attemptAddScripts(results, "Hashtag"))
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 60, in attemptAddScripts
    videoURL = tiktok["itemInfos"]["video"]["urls"][0]
KeyError: 'itemInfos'
'itemInfos'
exception occured downloading. waiting and retrying

Its happening a lot
