### ISSUE TITLE
ERROR when launch tiktok client main.py

### ISSUE THREAD

**Issue by Djaber317** [HA6Bots/TikTok-Compilation-Video-Generator#30]
Found config in location C:\Users\AEK INFO\Downloads\TikTok-Compilation-Video-Generator-master\TikTok-Compilation-Video-Generator-master\TikTok Client\config.ini
Found config in location C:\Users\AEK INFO\Downloads\TikTok-Compilation-Video-Generator-master\TikTok-Compilation-Video-Generator-master\TikTok Client\config.ini
<class 'requests.exceptions.ConnectionError'> ('Connection aborted.', BadStatusLine('J\x00\x00\x00\n')) <traceback object at 0x000002CE84655B48>
Traceback (most recent call last):
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1369, in getresponse
    response.begin()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 292, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: J

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1369, in getresponse
    response.begin()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 292, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('J\x00\x00\x00\n'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 71, in <module>
    client.requestGames()
  File "C:\Users\AEK INFO\Downloads\TikTok-Compilation-Video-Generator-master\TikTok-Compilation-Video-Generator-master\TikTok Client\client.py", line 19, in requestGames
    responsegames =requests.get(f'http://{httpaddress}/getgames')
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\AEK INFO\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('J\x00\x00\x00\n'))

**Comment by Djaber317** [comment]
Please Help me !

**Comment by stringgepa** [comment]
same error
