### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by innovadorx** [HA6Bots/TikTok-Compilation-Video-Generator#4]
Traceback (most recent call last):
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 150, in getAllClips
    new_ids.append(attemptAddScripts(results, "Hashtag"))
  File "D:\TikTok-Compilation-Video-Generator-master\TikTok Server\tiktok.py", line 60, in attemptAddScripts
    videoURL = tiktok["itemInfos"]["video"]["urls"][0]
KeyError: 'itemInfos'
'itemInfos'
exception occured downloading. waiting and retrying

Its happening a lot

_Originally posted by @innovadorx in https://github.com/HA6Bots/TikTok-Compilation-Video-Generator/issues/3#issuecomment-722738034_

**Comment by innovadorx** [comment]
it happens when i try to download by hashtag, if i choose any other option like trending it wont happen

**Comment by innovadorx** [comment]
I think TikTokApi made a lot of changes, thats why its not working correctly now. 

Found 10 unique clips
Downloading...
Downloading Clip 1/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 2/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 3/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 4/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 5/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 6/10
video generator offline
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 7/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 8/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 9/10
HTTP Error 403: Forbidden
Error downloading clip
Downloading Clip 10/10
HTTP Error 403: Forbidden
Error downloading clip

I get that error when trying to download clips searching by Author

**Comment by HA6Bots** [comment]
Ok I'm going to review the changes this weekend and make sure everything is updated for the new TikTokAPI version.
Please stay posted.

**Comment by innovadorx** [comment]
Thank you!

**Comment by HA6Bots** [comment]
API Fix! Please try again now with new server code.
